### ISSUE TITLE
Some typesetting lines was skipped

### ISSUE THREAD

**Issue by shinchiro** [tp7/Sushi#10]
Somehow some typesetting line was skipped. I dont know if its sushi's limitation or bugs but I think its better to let you know it:

Here is sample: http://www.datafilehost.com/d/60e4fecc

Check Line 5531 (text: rumble)

**Comment by shinchiro** [comment]
After investigate more, the problem came from extracted script itself. For a reason, the script which automatically extract by sushi contain less line than extracted manually by mkvextract

**Comment by tp7** [comment]
All right, this happens because ffmpeg is a moron and `-scodec copy` causes it to output a broken file. Since the only use for `-scodec copy` is [this issue](https://github.com/tp7/Sushi/issues/5) which never got anywhere, I guess I'll just remove it
