### ISSUE TITLE
Script encoded as UTF-8 without BOM

### ISSUE THREAD

**Issue by shinchiro** [tp7/Sushi#11]
Currently, sushi produced script which encoded with UTF-8 without BOM. Such character is like '—' (U+2014). When you drag the script inside player, it still display correctly. But after muxed the script with video, the character no longer display correctly. Encoding it as UTF-8 will solve the problem

**Comment by tp7** [comment]
I cannot reproduce the issue on my current setup but writing UTF-8 with BOM when we're reading it with BOM is indeed more reasonable and it doesn't break my regression tests.

**Comment by shinchiro** [comment]
I guess this issue only occur in some scripts. Here's some pic:

http://screenshotcomparison.com/comparison/107431
