### ISSUE TITLE
ZeroDivisionError: Weights sum to zero, can't be normalized

### ISSUE THREAD

**Issue by shinchiro** [tp7/Sushi#12]
Encountered this error when testing a file:
http://www.datafilehost.com/d/d0cb08e1

Running in Sushi 0.4.3..

**Comment by tp7** [comment]
I'll also need the chapters. Sushi doesn't extract them to a separate file automatically, you can do this with mkvextract(gui).

**Comment by shinchiro** [comment]
chapters:
http://www.datafilehost.com/d/a826697c

**Comment by shinchiro** [comment]
thanks for fixing this problem. Anyhow when can I expect new release with this bug fixed

**Comment by tp7** [comment]
You can try [this build](https://dl.dropboxusercontent.com/u/54253260/Sushi.0.4.3b.7z), I won't be releasing a new official version for every minor update.

**Comment by shinchiro** [comment]
thx, but I still getting the same error when trying other video:

Traceback (most recent call last):
  File "sushi.py", line 730, in <module>
  File "sushi.py", line 723, in parse_args_and_run
  File "sushi.py", line 603, in run
  File "sushi.py", line 314, in average_shifts
  File "numpy\lib\function_base.pyo", line 539, in average
ZeroDivisionError: Weights sum to zero, can't be normalized

**Comment by tp7** [comment]
You get same error every time one of the chapter groups ended up empty (all evens in there are linked to others). I'd have to look at your other sample to determine if it's the same kind of error or a completely different one.

**Comment by shinchiro** [comment]
Here's sample:
http://www.datafilehost.com/d/c6563a21

**Comment by tp7** [comment]
It was a completely different error - this one happened because your script had a chapter group with a single comment it in. Fixed in [this build](https://dl.dropboxusercontent.com/u/54253260/Sushi.0.4.3c.7z).
