### ISSUE TITLE
Support [Aegisub Extradata] section

### ISSUE THREAD

**Issue by shinchiro** [tp7/Sushi#19]
Currently sushi throw out of index error. I guess its because sushi unable to handle the extradata's section:

http://www.solidfiles.com/d/4bfede5221/[Anime-Koi]_Kami-sama_Hajimemashita_2_-_05_(Script).rar

One thing I noticed, when ffmpeg extract script with that section, it put [Aegisub Extradata] under [Events] but when I extract with mkvcleaver, [Aegisub Extradata] and [Events] section is separated as expected.

**Comment by tp7** [comment]
Fixed the issue with mkvcleaver's output and reported the bug to ffmpeg since it produces a clearly broken script. This should be fixed in one of the future ffmpeg releases. Thanks for the report.
