### ISSUE TITLE
Error with ASS scripts containing a [Aegisub Extradata] section

### ISSUE THREAD

**Issue by Nyx0uf** [tp7/Sushi#25]
The error thrown by sushi is : `That's some invalid ASS script: list index out of range`

Tried with Commie's Tsukimonogatari (All 4 eps contain a [Aegisub Extradata] section)

**Comment by tp7** [comment]
Just tried all four episodes and the scripts loaded fine. Can you provide any of the files that fail? Also, are you using the latest master or some Windows build?

**Comment by Nyx0uf** [comment]
I was using release 0.4.3 on OS X 10.10.

Totally missed there was a newer 0.4.4.

Sorry for the bother.
