### ISSUE TITLE
Change main .py shebang line

### ISSUE THREAD

**Issue by 4re** [tp7/Sushi#28]
I wonder if you would mind changing `sushi.py`'s shebang line to `#!/usr/bin/env python2`.
In any system that has `python3` as it's main python interpreter this error will be thrown as things are right now:
```
Traceback (most recent call last):
  File "/usr/local/bin/sushi", line 9, in <module>
    from itertools import takewhile, izip, chain
ImportError: cannot import name 'izip'
```

**Comment by tp7** [comment]
Done.
