### ISSUE TITLE
Exception: Circular link detected

### ISSUE THREAD

**Issue by shinchiro** [tp7/Sushi#9]
Get this error when try to shift sub. Is there any workaround for this?
Sample:
http://www.datafilehost.com/d/97bfce15

**Comment by tp7** [comment]
This is a bug but you'll have to provide both audio files and the script. More info here: https://github.com/tp7/Sushi/wiki/Common-errors#how-to-report-a-bug

**Comment by shinchiro** [comment]
here another audio with cli script:
http://www.datafilehost.com/d/5d3ab891

**Comment by tp7** [comment]
The subtitles script, not the cli script... How am I supposed to fix something in subtitles without said subtitles?

**Comment by shinchiro** [comment]
sub: http://www.datafilehost.com/d/4026525c

**Comment by tp7** [comment]
Just updated the Windows build, you can redownload it [here](https://github.com/tp7/Sushi/releases/tag/0.4.2). Should fix your issue.

**Comment by shinchiro** [comment]
Yeah its working fine. Thanx
